### ISSUE TITLE
Samsung Apps ActivityNotFound

### ISSUE THREAD

**Issue by silent1** [onepf/OpenIAB#147]
I looked through the code and it does exactly what the Samsung tutorial says so I'm not sure why this error would come up. In my version of OpenIAB, SamsungApps is chosen as the installer if the installer package name is com.sec.android.app.samsungapps, so maybe they're behind on updating the docs.

Raw stacktrace: 
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.sec.android.iap/com.sec.android.iap.activity.AccountActivity}; have you declared this activity in your AndroidManifest.xml?
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1512)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1388)
at android.app.Activity.startActivityForResult(Activity.java:3195)
at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:817)
at org.onepf.oms.appstore.SamsungAppsBillingService.startSetup(SamsungAppsBillingService.java:163)
at org.onepf.oms.OpenIabHelper$1.run(OpenIabHelper.java:326)

**Comment by akarimova** [comment]
Outdated.
