### ISSUE TITLE
error signature purchase item -1003

### ISSUE THREAD

**Issue by TobyKaos** [onepf/OpenIAB#357]
Hello,

I am testing purchase on differents stores and when I have bought an item I have received error code -1003.

It was a consumable item. I have bought a non consumable without error.

If I restart the game then querying past purchase solve issue and item purchase is handle correctly and I received coins I bought.

Test:
1/ have installed aptoide and 1mobile market
2/ download jetpack high from 1mobile
3/ launch the game and in the store buy a starter pack
4/ in logcat you can see error -1003
5/ restart the game by killing process
6/ starter pack is correctly handle.

I have test purcahse by installing directly from aptoide without issue.

**Comment by AntonGitName** [comment]
Hello, TobyKaos!

I have tried to install Jetpack High on two devices, but, unfortunately, I was not able to reproduce a problem you have specified. If I install the app through Google play then it runs normally, but If I do so through 1mobile I get NPE as soon as I start the application.

**Comment by TobyKaos** [comment]
Hello Anton,

it was with openiab 0.9.8.2. Now this issue seems to have disappear with 0.9.8.3.

In my google analytics today I can see:

For 1185 error purchase: 
72% error -1005
22% error -1002
4%  error 6

-1005 is user cancel I think.

Else i have many error at startup at the same time:

For 10075 error
99.79% error 3   (BILLING_RESPONSE_RESULT_BILLING_UNAVAILABLE)


in a nutshell
In one month 89% of error is at startup. 10075 error is very huge.

I have fix it but many of my user do not update they app (many of them comes from aptoide that is very bad for that).

**Comment by TobyKaos** [comment]
What is NPE?

**Comment by AntonGitName** [comment]
By NPE I mean NullPointerException. I run your app and then saved the log to see what happened. Here are some lines from the log:

    02-13 17:53:02.867  32327-32327/? D/CHAOS_ENGINE﹕ Creating IAB helper.
    02-13 17:53:02.872  32327-32327/? D/CHAOS_ENGINE﹕ Starting setup.
    ...
    02-13 17:53:07.072  32327-32348/? W/ContextImpl﹕ Implicit intents with startService are not safe: Intent { act=org.onepf.oms.billing.BIND } android.content.ContextWrapper.bindService:528 c.a.a.a.a.d.a:-1 c.a.a.k.run:-1

    02-13 17:53:07.082  32327-32327/? D/CHAOS_ENGINE﹕ Setup finished.
    02-13 17:53:07.082  32327-32327/? D/CHAOS_ENGINE﹕ Setup successful. Querying inventory.

    02-13 17:53:07.552  32327-32548/? W/dalvikvm﹕ threadid=26: thread exiting with uncaught exception (group=0x41723c08)
    02-13 17:53:07.552  32327-32548/? E/AndroidRuntime﹕ FATAL EXCEPTION: Thread-38076
        Process: com.chaosinteractive.jetpackhigh, PID: 32327
        java.lang.NullPointerException
                at android.os.Parcel.readException(Parcel.java:1471)
                at android.os.Parcel.readException(Parcel.java:1419)
                at c.a.a.i.a(Unknown Source)
                at c.a.a.a.i.a(Unknown Source)
                at c.a.a.a.a.d.a(Unknown Source)
                at c.a.a.a.a.d.a(Unknown Source)
                at c.a.a.j.a(Unknown Source)
                at c.a.a.q.run(Unknown Source)
                at java.lang.Thread.run(Thread.java:841)

    ...            
    02-13 17:53:08.322  32327-32327/? D/CHAOS_ENGINE﹕ Destroying helper.
    ...

It looks like OpenIAB works without errors and one of your methods throws an exception.

As for error codes, this might be helpful:

    IABHELPER_ERROR_BASE = -1000;
    IABHELPER_REMOTE_EXCEPTION = -1001;
    IABHELPER_BAD_RESPONSE = -1002;
    IABHELPER_VERIFICATION_FAILED = -1003;
    IABHELPER_SEND_INTENT_FAILED = -1004;
    IABHELPER_USER_CANCELLED = -1005;
    IABHELPER_UNKNOWN_PURCHASE_RESPONSE = -100
    IABHELPER_MISSING_TOKEN = -1007;
    IABHELPER_UNKNOWN_ERROR = -1008;
    IABHELPER_SUBSCRIPTIONS_NOT_AVAILABLE = -1
    IABHELPER_INVALID_CONSUMPTION = -1010;

**Comment by TobyKaos** [comment]
Yes Openiab seems to works. As I said with the update of openiab I have not encounter again the error code -1002.

But indeed my game crash. What is your phone and android version? What version of Jetpack High.

thank you

**Comment by AntonGitName** [comment]
I was testing the app on Samsung Galaxy Note 3 SM-N900. Android version is 4.4.2. Jetpack High's version is 1.7.0.57.

**Comment by akarimova** [comment]
Hi @TobyKaos 
what do you mean by 

>But indeed my game crash. What is your phone and android version? What version of Jetpack High.

? the mentioned NPE?

**Comment by TobyKaos** [comment]
I think NPE is not due to openiab. I will check my code soon.
