### ISSUE TITLE
IAB helper setup failed. Can't perform operation

### ISSUE THREAD

**Issue by iliyard** [onepf/OpenIAB#381]
I used openiab-plugin-0.9.7.2.unitypackage
Unity version : 4.5.2f

There are so many crash..
Please help me..

- Error
java.lang.Error: FATAL EXCEPTION [main]
Unity version : 4.5.2f1
Device model : Sony D2306
Device fingerprint: Sony/D2306/D2306:4.4.2/18.3.C.0.37/2n9_bg:user/release-keys

Caused by: java.lang.IllegalStateException: IAB helper setup failed. Can't perform operation: queryInventoryAsync
at org.onepf.oms.OpenIabHelper.checkSetupDone(OpenIabHelper.java:992)
at org.onepf.oms.OpenIabHelper.queryInventoryAsync(OpenIabHelper.java:908)
at org.onepf.openiab.UnityPlugin$2.run(UnityPlugin.java:152)
at android.os.Handler.handleCallback(Handler.java:743)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5212)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
at dalvik.system.NativeStart.main(Native Method)

- Crash Devices
AQUOS Xx 304SH(SG304SH)	10	11.6%
AQUOS PHONE Xx 302SH(SBM302SH)	10	11.6%
SoftBank AQUOS PHONE Xx 203SH(SBM203SH)	9	10.5%
AQUOS PHONE Xx mini 303SH(SBM303SH)	8	9.3%
ARROWS A SoftBank 301F(SBM301F)	4	4.7%
Optimus L5(m4)	3	3.5%
ALCATEL ONE TOUCH 5035D(Camry_GSM)	3	3.5%
Galaxy Grand duos(baffin)	2	2.3%
Essentielb- Black Diamond(bird77_a_cu_ics2)	2	2.3%
E860(E860)	2	2.3%
ARROWS X LTE F-05D(blaze)	2	2.3%
hwh867g	2	2.3%
HTC One V(primou)	1	1.2%
Event(C5133)	1	1.2%
Xperia M2(D2306)	1	1.2%
mobitek77_m01_ics2	1	1.2%
Liquid Z3(ZX)	1	1.2%
Xperia E1(D2005)	1	1.2%
MIRACH_J(mirachj)	1	1.2%
ITP-R208W(rk30sdk)	1	1.2%
Galaxy Ace2(GT-I8160)	1	1.2%
Y330-U01(hwY330-U01)	1	1.2%
AQUOS PHONE SH-01D(SH01D)	1	1.2%
Galaxy Pocket Neo(corsicass)	1	1.2%
Galaxy S3(m0)	1	1.2%
URBANO PROGRESSO(KYY04)	1	1.2%
ALCATEL ONE TOUCH 5020D(Megane_GSM)	1	1.2%
AQUOS PHONE SH-06D(SH06D)	1	1.2%
Flyer(flyer)	1	1.2%
polaris-p1	1	1.2%
HTC Desire 600 Dual SIM(cp3dug)	1	1.2%
DM016SH(DM016SH)	1	1.2%
LG Optimus L3 II(vee3e)	1	1.2%
AQUOS PHONE Xx 206SH(SBM206SH)	1	1.2%
G2(vision)	1	1.2%
Xperia J(ST26i)	1	1.2%
ALCATEL ONE TOUCH 5020N(Megane)	1	1.2%
SHV-E110S(SHV-E110S)	1	1.2%
ONT TOUCH 4015X(Yaris35_GSM)	1	1.2%
Xperia L(C2105)	1	1.2%
A706(armani)	1	1.2%

**Comment by akarimova** [comment]
closed as outdated

**Comment by spacetraveller** [comment]
Issue is still active,  got a report from this just yesterday.
