### ISSUE TITLE
IllegalArgumentException at GooglePlay.isBillingAvailable() on some Android Lollipop devices

### ISSUE THREAD

**Issue by koAlech** [onepf/OpenIAB#393]
Hi there,
We've started receiving an IllegalArgumentException from some of of our Android L devices:
java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.android.vending.billing.InAppBillingService.BIND }
       at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1674)
       at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1773)
       at android.app.ContextImpl.bindService(ContextImpl.java:1751)
       at android.content.ContextWrapper.bindService(ContextWrapper.java:538)
       at org.onepf.oms.appstore.GooglePlay.isBillingAvailable(SourceFile:100)
       at org.onepf.oms.OpenIabHelper.selectBillingService(SourceFile:699)
       at org.onepf.oms.OpenIabHelper$1.run(SourceFile:392)
       at java.lang.Thread.run(Thread.java:818)

Googling the problem shows quite a lot of people complaining about this issue.
Such as http://commonsware.com/blog/2014/06/29/dealing-deprecations-bindservice.html

Thanks, Alik

**Comment by Solum** [comment]
I am currently using openiab-0.9.8.2.jar and still seeing this error:

java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=org.onepf.oms.billing.BIND }
  	at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1674)
  	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1773)
  	at android.app.ContextImpl.bindService(ContextImpl.java:1751)
  	at android.content.ContextWrapper.bindService(ContextWrapper.java:538)
  	at org.onepf.oms.appstore.googleUtils.IabHelper.startSetup(IabHelper.java:277)
  	at org.onepf.oms.OpenIabHelper$12$1.onIabSetupFinished(OpenIabHelper.java:830)
  	at org.onepf.oms.OpenIabHelper.finishSetup(OpenIabHelper.java:919)
  	at org.onepf.oms.OpenIabHelper.finishSetup(OpenIabHelper.java:888)
  	at org.onepf.oms.OpenIabHelper.access$1700(OpenIabHelper.java:82)
  	at org.onepf.oms.OpenIabHelper$12$2.run(OpenIabHelper.java:839)
  	at android.os.Handler.handleCallback(Handler.java:739)
  	at android.os.Handler.dispatchMessage(Handler.java:95)
  	at android.os.Looper.loop(Looper.java:135)
  	at android.app.ActivityThread.main(ActivityThread.java:5221)
  	at java.lang.reflect.Method.invoke(Native Method)
  	at java.lang.reflect.Method.invoke(Method.java:372)
  	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
