### ISSUE TITLE
wrong set up state  3

### ISSUE THREAD

**Issue by oneirosapps** [onepf/OpenIAB#396]
QueryInventoryFinishedListener is sucessfull
onActivityResult implemented
 still getting error 
java.lang.IllegalStateException: Wrong setup state: 3
       at org.onepf.oms.OpenIabHelper.setupStateToString(OpenIabHelper.java:1024)
       at org.onepf.oms.OpenIabHelper.checkSetupDone(OpenIabHelper.java:989)
       at org.onepf.oms.OpenIabHelper.launchPurchaseFlow(OpenIabHelper.java:783)
       at org.onepf.oms.OpenIabHelper.launchPurchaseFlow(OpenIabHelper.java:768)
       at com.oneiros.russianroulette.BuyHelper.onClick(BuyHelper.java:322)
       at com.oneiros.russianroulette.BuyHelper.onItemClick(BuyHelper.java:277)
       at android.widget.AdapterView.performItemClick(AdapterView.java:301)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1287)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3080)
       at android.widget.AbsListView.onTouchEvent(AbsListView.java:4176)
       at android.view.View.dispatchTouchEvent(View.java:7393)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2462)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2195)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2468)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2210)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2468)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2210)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2468)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2210)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2468)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2210)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2468)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2210)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2177)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1482)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2470)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2125)
       at android.view.View.dispatchPointerEvent(View.java:7578)
       at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3571)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3503)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4614)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4592)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4696)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:171)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:125)
       at android.os.Looper.loop(Looper.java:138)
       at android.app.ActivityThread.main(ActivityThread.java:4947)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by akarimova** [comment]
@oneirosapps 
is it still actual?

**Comment by oneirosapps** [comment]
sometimes this issue is coming from live apps
