### ISSUE TITLE
OpenIabHelper.Options.SEARCH_STRATEGY_INSTALLER_THEN_BEST_FIT crashes

### ISSUE THREAD

**Issue by adryamov** [onepf/OpenIAB#398]
The new strategy of discovering app stores doesn't take into account that Amazon classes is not supplied with the build. This happen when the application is installed on device with "amazon store app", but without installer set and with OpenIabHelper.Options.SEARCH_STRATEGY_INSTALLER_THEN_BEST_FIT strategy. When OpenIabHelper trying to dispose AmazonAppStore

        @Override
        public void onIabSetupFinished(final IabResult result) {
            // Dispose of all initialized open app stores
            final Collection<Appstore> appstoresToDispose = new ArrayList<Appstore>(appstores);
            if (foundAppstore != null) {
                appstoresToDispose.remove(foundAppstore);
            }
            dispose(appstoresToDispose); //!!!! here
            if (foundAppstore != null) {
                foundAppstore.getInAppBillingService().startSetup(listener);
            } else {
                listener.onIabSetupFinished(result);
            }
        }

we get crash with the given stacktrace:

java.lang.NoClassDefFoundError: org.onepf.oms.appstore.AmazonAppstoreBillingService
	at org.onepf.oms.appstore.AmazonAppstore.getInAppBillingService(AmazonAppstore.java:90)
	at org.onepf.oms.OpenIabHelper.dispose(OpenIabHelper.java:834)
	at org.onepf.oms.OpenIabHelper.access$1600(OpenIabHelper.java:82)
	at org.onepf.oms.OpenIabHelper$12$1.onIabSetupFinished(OpenIabHelper.java:811)
	at org.onepf.oms.OpenIabHelper.finishSetup(OpenIabHelper.java:901)
	at org.onepf.oms.OpenIabHelper.finishSetup(OpenIabHelper.java:870)
	at org.onepf.oms.OpenIabHelper.access$1700(OpenIabHelper.java:82)
	at org.onepf.oms.OpenIabHelper$12$2.run(OpenIabHelper.java:822)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5221)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

Before that we have in logcat:

I/art(15975): Rejecting re-init on previously-failed class java.lang.Class<org.onepf.oms.appstore.AmazonAppstoreBillingService>

This issue is related to closed one #230. When discovering available app stores we need to check not only the availability of the service of this store, but the validity of using it (for instance for AmazonAppStore we need to check hasAmazonClasses()).

**Comment by akarimova** [comment]
https://github.com/onepf/OpenIAB/wiki/How-To-add-OpenIAB-to-an-app
