### ISSUE TITLE
NoClassDefFoundError: AmazonAppstoreBillingService in 0.9.8

### ISSUE THREAD

**Issue by ataulm** [onepf/OpenIAB#400]
Has the usage of the library changed since the last version? In 0.9.8 (I tried this using the `compile 'org.onepf:openiab:0.9.8'` and also building the `aar` from master myself), I get an error:

```
11-25 13:45:04.350    1503-1503/com.myapp E/dalvikvm﹕ Could not find class 'org.onepf.oms.appstore.AmazonAppstoreBillingService', referenced from method org.onepf.oms.appstore.AmazonAppstore.getInAppBillingService
11-25 13:45:04.406    1503-1503/com.myapp E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: org.onepf.oms.appstore.AmazonAppstoreBillingService
            at org.onepf.oms.appstore.AmazonAppstore.getInAppBillingService(AmazonAppstore.java:90)
            at org.onepf.oms.OpenIabHelper.finishSetup(OpenIabHelper.java:908)
            at org.onepf.oms.OpenIabHelper.finishSetup(OpenIabHelper.java:880)
            at org.onepf.oms.OpenIabHelper.access$1700(OpenIabHelper.java:82)
            at org.onepf.oms.OpenIabHelper$12$2.run(OpenIabHelper.java:831)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5041)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
```

Looking in `master` this class is still present, and public. Has the building of the library changed since version at commit c3ff201a585de5b6db3e99727eb523ea75f222ec in such a way as to effect this error?

**Comment by hacketo** [comment]
I got the same stack-trace when the OpenIabHelper startSetup With YANDEX store only.
How could I handle that ?  I don't have any gradle or maven config.

**Comment by RomanZhilich** [comment]
Please make sure you're using latest release version. All this dependencies should be optional.
