### ISSUE TITLE
java.lang.IllegalArgumentException: Service Intent must be explicit on Android 5.0

### ISSUE THREAD

**Issue by Sachinx0e** [onepf/OpenIAB#415]
I have been getting crash reports with following errors on LG Nexus 5 devices with Android 5.0. The crashes do not occur on all devices and I am not able to reproduce them on my side.

``` java
java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.android.vending.billing.InAppBillingService.BIND }
       at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1674)
       at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1773)
       at android.app.ContextImpl.bindService(ContextImpl.java:1751)
       at android.content.ContextWrapper.bindService(ContextWrapper.java:538)
       at org.onepf.oms.appstore.GooglePlay.isBillingAvailable(GooglePlay.java:134)
       at org.onepf.oms.OpenIabHelper$12.run(OpenIabHelper.java:806)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

I think this issue was fixed here  https://github.com/onepf/OpenIAB/issues/393 , but I am still seeing the crashes.

**Comment by Solum** [comment]
I am currently using openiab-0.9.8.2.jar and still seeing this error:

java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=org.onepf.oms.billing.BIND }
at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1674)
at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1773)
at android.app.ContextImpl.bindService(ContextImpl.java:1751)
at android.content.ContextWrapper.bindService(ContextWrapper.java:538)
at org.onepf.oms.appstore.googleUtils.IabHelper.startSetup(IabHelper.java:277)
at org.onepf.oms.OpenIabHelper$12$1.onIabSetupFinished(OpenIabHelper.java:830)
at org.onepf.oms.OpenIabHelper.finishSetup(OpenIabHelper.java:919)
at org.onepf.oms.OpenIabHelper.finishSetup(OpenIabHelper.java:888)
at org.onepf.oms.OpenIabHelper.access$1700(OpenIabHelper.java:82)
at org.onepf.oms.OpenIabHelper$12$2.run(OpenIabHelper.java:839)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5221)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by Solum** [comment]
I have tried with openiab-0.9.8.3.jar and got again the samer error. I then reverted back my targetSdkVersion from "21" to "19". It now works. Tested with Google Play Store and Aptoide.

So there's definitely a problem with pointing to Android Lollipop.

**Comment by RomanZhilich** [comment]
Can anyone please try latest build from master and try to reproduce this issue?
https://yadi.sk/d/hugMOgiZeye9y

**Comment by sdeff** [comment]
I'm getting the same error with 0.9.8.6. I would like to test your 0.9.8.7 SNAPSHOT. Is it safe to use that SNAPSHOT in production? (In oder words: Did you only apply your mentioned workaround to it?)

**Comment by RomanZhilich** [comment]
Yes, above link contains possible workaround. As for it being safe for production use... We tested it the best we could, and you can always take a look through code yourself.
