### ISSUE TITLE
java.lang.IllegalArgumentException: Service Intent must be explicit caused by amazon 2.0.0

### ISSUE THREAD

**Issue by friedger** [onepf/OpenIAB#418]
java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.amazon.testclient.iap.appUserId flg=0x10000000 (has extras) }
            at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1674)
            at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1703)
            at android.app.ContextImpl.startService(ContextImpl.java:1687)
            at android.content.ContextWrapper.startService(ContextWrapper.java:515)
            at com.amazon.device.iap.internal.a.c.a(SandboxRequestHandler.java:87)
            at com.amazon.device.iap.internal.a.c.a(SandboxRequestHandler.java:69)
            at com.amazon.device.iap.internal.d.c(PurchasingManager.java:71)
            at com.amazon.device.iap.PurchasingService.getUserData(PurchasingService.java:69)
            at org.onepf.oms.appstore.AmazonAppstoreBillingService.startSetup(AmazonAppstoreBillingService.java:134)
            at org.onepf.oms.OpenIabHelper$12$1.onIabSetupFinished(OpenIabHelper.java:813)
            at org.onepf.oms.OpenIabHelper.finishSetup(OpenIabHelper.java:901)
            at org.onepf.oms.OpenIabHelper.finishSetup(OpenIabHelper.java:870)
            at org.onepf.oms.OpenIabHelper.access$1700(OpenIabHelper.java:82)
            at org.onepf.oms.OpenIabHelper$12$2.run(OpenIabHelper.java:822)

**Comment by akarimova** [comment]
@friedger 
could you please check out out latest master? Roman made a wrapper to prevent this crash.

**Comment by akarimova** [comment]
fixed
