### ISSUE TITLE
unexpected RejectedExecutionException

### ISSUE THREAD

**Issue by 4apogeu** [onepf/OpenIAB#425]
Hi!

https://github.com/onepf/OpenIAB/issues/406

I try to use unity plugin v 0.9.8.2, but the problem still exists:

java.lang.Error: FATAL EXCEPTION [main]
Unity version : 4.6.1f1
Device model : htc Nexus 9
Device fingerprint: google/volantis/flounder:5.0.1/LRX22C/1602158:user/release-keys

Caused by: java.util.concurrent.RejectedExecutionException: Task org.onepf.oms.OpenIabHelper$15$1@15956848 rejected from java.util.concurrent.ThreadPoolExecutor@261386e1[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:583)
at org.onepf.oms.OpenIabHelper$15.onIabSetupFinished(OpenIabHelper.java:1141)
at org.onepf.oms.appstore.googleUtils.IabHelper$1.onServiceConnected(IabHelper.java:267)
at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1203)
at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1220)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5221)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by RomanZhilich** [comment]
Are you sure this crash log belong to 0.9.8.2? There doesn't seem to be anything related to executor here [OpenIabHelper.java:1141](https://github.com/onepf/OpenIAB/blob/0.9.8.2/library/src/main/java/org/onepf/oms/OpenIabHelper.java#L1141).

However it looks like ```inventoryExecutor``` throws this exception for some reason.. And I have no idea why and how to fix it.
Try to find reliable way to reproduce this crash, maybe multiple ```quieryInventory()``` call or something...

**Comment by akarimova** [comment]
Hi @4apogeu,
any updates?

**Comment by 4apogeu** [comment]
Hi!

I rebuild my project and now everything is ok!
