### ISSUE TITLE
problem: Yandex store [Acer IconiaTab 8]

### ISSUE THREAD

**Issue by Sergey-Shpital** [onepf/OpenIAB#434]
01-16 21:52:19.120: E/[YandexAccountManager].[f](1776): Error while querying version
01-16 21:52:19.120: E/[YandexAccountManager].[f](1776): java.lang.SecurityException: Permission Denial: reading com.yandex.auth.store.AccountProvider uri content://com.yandex.auth.store/lib from pid=8670, uid=10199 requires com.yandex.permission.READ_CREDENTIALS, or grantUriPermission()
01-16 21:52:19.120: E/[YandexAccountManager].[f](1776): 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:467)
01-16 21:52:19.120: E/[YandexAccountManager].[f](1776): 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:394)
01-16 21:52:19.120: E/[YandexAccountManager].[f](1776): 	at android.content.ContentProvider$Transport.query(ContentProvider.java:194)
01-16 21:52:19.120: E/[YandexAccountManager].[f](1776): 	at android.content.ContentResolver.query(ContentResolver.java:461)
01-16 21:52:19.120: E/[YandexAccountManager].[f](1776): 	at android.content.ContentResolver.query(ContentResolver.java:404)
01-16 21:52:19.120: E/[YandexAccountManager].[f](1776): 	at com.yandex.auth.sync.database.f.b(SourceFile:57)
01-16 21:52:19.120: E/[YandexAccountManager].[f](1776): 	at com.yandex.auth.sync.h.a(SourceFile:51)
01-16 21:52:19.120: E/[YandexAccountManager].[f](1776): 	at com.yandex.auth.sync.h.a(SourceFile:72)
01-16 21:52:19.120: E/[YandexAccountManager].[f](1776): 	at com.yandex.auth.m.a(SourceFile:18)
01-16 21:52:19.120: E/[YandexAccountManager].[f](1776): 	at com.yandex.auth.YandexAccountManager.from(SourceFile:12)
01-16 21:52:19.120: E/[YandexAccountManager].[f](1776): 	at me.f(SourceFile:114)
01-16 21:52:19.120: E/[YandexAccountManager].[f](1776): 	at me.e(SourceFile:109)
01-16 21:52:19.120: E/[YandexAccountManager].[f](1776): 	at me.j(SourceFile:244)
01-16 21:52:19.120: E/[YandexAccountManager].[f](1776): 	at us.a(SourceFile:136)
01-16 21:52:19.120: E/[YandexAccountManager].[f](1776): 	at us.a(SourceFile:55)
01-16 21:52:19.120: E/[YandexAccountManager].[f](1776): 	at com.yandex.store.service.YandexStoreService$4.isBillingAvailable(SourceFile:274)
01-16 21:52:19.120: E/[YandexAccountManager].[f](1776): 	at org.onepf.oms.IOpenAppstore$Stub.onTransact(SourceFile:74)
01-16 21:52:19.120: E/[YandexAccountManager].[f](1776): 	at android.os.Binder.execTransact(Binder.java:404)
01-16 21:52:19.120: E/[YandexAccountManager].[f](1776): 	at dalvik.system.NativeStart.run(Native Method)

**Comment by akarimova** [comment]
Hi @Sergey-Shpital,
it is a YS bug. We don't have any workaround...
This issue was reported to the YS guys.

Please don't close it, let's save it as a known issue.

**Comment by Sergey-Shpital** [comment]
ok, I see
