### ISSUE TITLE
Amazon and Android 5.0

### ISSUE THREAD

**Issue by Shyri** [onepf/OpenIAB#456]
Hi!
In the "readme" section you say there are some issues with Amazon SDK and Android 5.0. Reading the Amazon official page, I understand it has been fixed by January the 8th buy I'm not quite sure. Please, could you confirm this?

https://developer.amazon.com/public/apis/earn/in-app-purchasing/docs-v2/whats-new-in-in-app-purchasing

Thank you very much in advance

**Comment by RomanZhilich** [comment]
Hello.
We still use Amazon in-app 2.0.1 and ugly workaround to support Lollipop: #433 
We'll probably update to latest Amazon library in our next release, thanks.

**Comment by akarimova** [comment]
https://github.com/onepf/OpenIAB/releases/tag/0.9.8.6 - with the workaround

**Comment by clorteau** [comment]
Hi. On 0.9.8.6 and 0.9.8.7 I still get this bug. Phone is Galaxy S6 with lollipop 5.0.2.

java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=org.onepf.oms.billing.BIND }
            at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:2053)
            at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:2161)
            at android.app.ContextImpl.bindService(ContextImpl.java:2139)
            at android.content.ContextWrapper.bindService(ContextWrapper.java:559)
            at org.onepf.oms.appstore.googleUtils.IabHelper.startSetup(IabHelper.java:277)
            at org.onepf.oms.OpenIabHelper$12$1.onIabSetupFinished(OpenIabHelper.java:863)
            at org.onepf.oms.OpenIabHelper.finishSetup(OpenIabHelper.java:952)
            at org.onepf.oms.OpenIabHelper.finishSetup(OpenIabHelper.java:921)
            at org.onepf.oms.OpenIabHelper.access$1800(OpenIabHelper.java:85)
            at org.onepf.oms.OpenIabHelper$12$2.run(OpenIabHelper.java:872)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:6117)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
