### ISSUE TITLE
Attempt to reopen closed database

### ISSUE THREAD

**Issue by silent1** [onepf/OpenIAB#468]
java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/data/com.forpda.lp/databases/BillingRestoreTransactions
	at android.os.Parcel.readException(Parcel.java:1473)
	at android.os.Parcel.readException(Parcel.java:1419)
	at com.android.vending.billing.IInAppBillingService$Stub$Proxy.getPurchases(IInAppBillingService.java:358)
	at org.onepf.oms.appstore.googleUtils.IabHelper.queryPurchases(IabHelper.java:901)
	at org.onepf.oms.appstore.googleUtils.IabHelper.queryInventory(IabHelper.java:580)
	at org.onepf.oms.OpenIabHelper.queryInventory(OpenIabHelper.java:1303)
	at org.onepf.oms.OpenIabHelper$17.run(OpenIabHelper.java:1355)
	at java.lang.Thread.run(Thread.java:841)

**Comment by RomanZhilich** [comment]
Seems like an error in Google Implementation of IInAppBillingService. What was the version/model of device it occurred on?

**Comment by silent1** [comment]
Samsung GT-I9505, Android 4.4.2. It was on a user's device so I'm not sure how to reproduce it.

**Comment by RomanZhilich** [comment]
I'm afraid there's not much I can do.
I'll close this issue for now, please reopen it if you find a reliable way to reproduce it so I could look for a workaround.
