### ISSUE TITLE
Unexpected response code 500 for Yandex

### ISSUE THREAD

**Issue by Edison4** [onepf/OpenIAB#478]
04-21 09:02:17.172    4676-4706/com.yandex.store E/Volley﹕ [277] ac.a: Unexpected response code 500 for https://mobile.store.yandex.net/api/v3/products
04-21 09:02:17.172    4676-4762/com.yandex.store W/Yandex.store-15443﹕ w
    java.util.concurrent.ExecutionException: w
            at as.a(SourceFile:117)
            at as.get(SourceFile:88)
            at nr.a(SourceFile:73)
            at uw.a(SourceFile:29)
            at uw.c(SourceFile:11)
            at com.yandex.store.service.CommandIntentService.a(SourceFile:44)
            at com.yandex.store.service.YandexStoreService$2.getSkuDetails(SourceFile:142)
            at com.yandex.store.service.YandexStoreService$3.getSkuDetails(SourceFile:206)
            at org.onepf.oms.IOpenInAppBillingService$Stub.onTransact(SourceFile:75)
            at android.os.Binder.execTransact(Binder.java:367)
            at dalvik.system.NativeStart.run(Native Method)
     Caused by: w
            at ac.a(SourceFile:146)
            at i.run(SourceFile:110)
04-21 09:02:17.172  15037-15067/dev.mabee.iwant E/OpenIAB﹕ queryInventoryAsync() Error :
    org.onepf.oms.appstore.googleUtils.IabException: Error refreshing inventory (querying prices of items). (response: 6:Error)
            at org.onepf.oms.appstore.googleUtils.IabHelper.queryInventory(IabHelper.java:588)
            at org.onepf.oms.OpenIabHelper.queryInventory(OpenIabHelper.java:1410)
            at org.onepf.oms.OpenIabHelper$17.run(OpenIabHelper.java:1462)
            at java.lang.Thread.run(Thread.java:856)

**Comment by Edison4** [comment]
Why?

**Comment by akarimova** [comment]
The most likely cause - you don't have any active SKU for your app on the dev console.

**Comment by akarimova** [comment]
Please check it.

**Comment by PankovSerge** [comment]
Same issue with OpenIAB. I have one in-app, and it is active on this moment,  was created 2 days ago. 
More than 4 times check public key, in-app, and other things ... 

18137-18170/? E/Volley﹕ [2057] ac.a: Unexpected response code 500 for https://mobile.store.yandex.net/api/v3/products
06-30 18:53:34.384  28883-28883/com.samecompany.sameapp D/OpenIAB﹕ handleActivityResult() requestCode: 10001 resultCode: -1 data: Intent { (has extras) }
06-30 18:53:34.384  28883-28883/com.samecompany.sameapp D/OpenIAB﹕ Ending async operation:
06-30 18:53:34.384  28883-28883/com.samecompany.sameapp D/OpenIAB﹕ Purchase canceled - Response: 6:Error
06-30 18:53:34.384  28883-28883/com.samecompany.sameapp D/OpenIAB﹕ Result code was OK but in-app billing response was not OK: 6:Error
06-30 18:53:34.412  28883-28883/com.samecompany.sameapp D/DEBUG﹕ OpenIAB error : Problem purchashing item. (response: 6:Error)
