### ISSUE TITLE
java.lang.IllegalMonitorStateException: object not locked by thread before notify()

### ISSUE THREAD

**Issue by nkuznetsow** [onepf/OpenIAB#481]
The exception was thrown on line 989 in OpenIabHelper class

https://github.com/onepf/OpenIAB/blob/master/library/src/main/java/org/onepf/oms/OpenIabHelper.java#L989

Possible countDownLatch.notify(); must be changed to countDownLatch.countDown();

Stack trace is: 

FATAL EXCEPTION: main
java.lang.IllegalMonitorStateException: object not locked by thread before notify()
at java.lang.Object.notify(Native Method)
at org.onepf.oms.OpenIabHelper$13.openStoresDiscovered(OpenIabHelper.java:990)
at org.onepf.oms.OpenIabHelper.discoverOpenStores(OpenIabHelper.java:1058)
at org.onepf.oms.OpenIabHelper.access$2000(OpenIabHelper.java:85)
at org.onepf.oms.OpenIabHelper$14.onServiceConnected(OpenIabHelper.java:1037)
at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1106)
at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1123)
at android.os.Handler.handleCallback(Handler.java:725)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:175)
at android.app.ActivityThread.main(ActivityThread.java:5279)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
at dalvik.system.NativeStart.main(Native Method)

**Comment by RomanZhilich** [comment]
You're absolutely right, it's a typo.
