### ISSUE TITLE
IAB helper setup failed. Can't perform operation: launchPurchaseFlow

### ISSUE THREAD

**Issue by moshkit** [onepf/OpenIAB#491]
This exception happens if user logout from system account and tries to buy some inapp. 

java.lang.IllegalStateException: IAB helper setup failed. Can't perform operation: launchPurchaseFlow
       at org.onepf.oms.OpenIabHelper.checkSetupDone(OpenIabHelper.java:992)
       at org.onepf.oms.OpenIabHelper.launchPurchaseFlow(OpenIabHelper.java:783)
       at org.onepf.oms.OpenIabHelper.launchSubscriptionPurchaseFlow(OpenIabHelper.java:778)
       at org.onepf.oms.OpenIabHelper.launchSubscriptionPurchaseFlow(OpenIabHelper.java:773)
 
I update library to the latest (0.9.8.6). Same behaviour.

Only solution that i found is to use try catch block on method "launchSubscriptionPurchaseFlow"
```java
		try {
			mOpenIabHelper.launchSubscriptionPurchaseFlow(...);
		} catch (Exception ex) {
			callback.onPurchaseFinished(false, null, null);
		}
```
I think this method should not throw an exception in case of user logout. because it is normal use case. 

Please handle this error inside library or use try{}catch{} in your sample application.

**Comment by RomanZhilich** [comment]
> at org.onepf.oms.OpenIabHelper.checkSetupDone(OpenIabHelper.java:992)

As you can see from the stacktrace, the problem is not with user being logout but with a library state. Apparently you don't handle setup callback properly. And crash is happens probably because library takes more time to setup when user is logout.

**Comment by RomanZhilich** [comment]
Looks like you're not handling setup callback properly. When user is not logged in library is probably takes a bit more time to setup.

**Comment by moshkit** [comment]
The sample app does not use try catch block for launchSubscription method. My app works fine with inApp. When I logout user from system account. it throws an exception and application was closed. I think this situation should be discribed in sample app.

**Comment by RomanZhilich** [comment]
> When I logout user from system account. it throws an exception

There should be no exception when user is logged out. Exception you get is intended to indicate developer mistakes. That's why there's no try/catch.

**Comment by moshkit** [comment]
I install application. buy some inApp.
Go to the settings - Accounts - Google - MyAcc@gmail.com - logout
Launch my app. try to buy some inapp.
Result:
java.lang.IllegalStateException: IAB helper setup failed. Can't perform operation: launchPurchaseFlow
Application fails.

Where is developer mistake here?

**Comment by RomanZhilich** [comment]
What application are you talking about?

**Comment by nanom1t** [comment]
java.lang.NullPointerException
net.mobfix.billing.IabHelper.startSetup(IabHelper.java:267)
net.mobfix.views.BuyCoinsDialog.initInAppBilling(BuyCoinsDialog.java:190)
net.mobfix.views.BuyCoinsDialog.onCreate(BuyCoinsDialog.java:142)
android.app.Dialog.dispatchOnCreate(Dialog.java:351)
android.app.Dialog.show(Dialog.java:256)
net.mobfix.riddles.GameActivity.showBuyCoinsDialog(GameActivity.java:286)
net.mobfix.riddles.GameActivity.access$100(GameActivity.java:57)
net.mobfix.riddles.GameActivity$3.onClick(GameActivity.java:140)
android.view.View.performClick(View.java:4084)
android.view.View$PerformClick.run(View.java:16989)
android.os.Handler.handleCallback(Handler.java:615)
android.os.Handler.dispatchMessage(Handler.java:92)
android.os.Looper.loop(Looper.java:137)
android.app.ActivityThread.main(ActivityThread.java:4813)
java.lang.reflect.Method.invokeNative(Native Method)
java.lang.reflect.Method.invoke(Method.java:511)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:559)
dalvik.system.NativeStart.main(Native Method)
