### ISSUE TITLE
SecurityException while binding 2

### ISSUE THREAD

**Issue by alex-dorokhov** [onepf/OpenIAB#497]
openiab 0.9.8.7

```java
java.lang.SecurityException: Not allowed to bind to service Intent { act=org.onepf.oms.openappstore.BIND cmp=com.yandex.store/.service.YandexStoreService }
       at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1675)
       at android.app.ContextImpl.bindService(ContextImpl.java:1639)
       at android.content.ContextWrapper.bindService(ContextWrapper.java:517)
       at org.onepf.oms.OpenIabHelper.discoverOpenStores(OpenIabHelper.java:1036)
       at org.onepf.oms.OpenIabHelper.discoverOpenStores(OpenIabHelper.java:1001)
       at org.onepf.oms.OpenIabHelper.setup(OpenIabHelper.java:694)
       at org.onepf.oms.OpenIabHelper.setupWithStrategy(OpenIabHelper.java:579)
       at org.onepf.oms.OpenIabHelper.startSetup(OpenIabHelper.java:550)
       at com.badlogic.gdx.pay.android.openiab.PurchaseManagerAndroidOpenIAB$1.run(PurchaseManagerAndroidOpenIAB.java:232)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5292)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by akarimova** [comment]
An outdated Yandex.Store apk, for the new version everything is OK.
How to fix: the store declares the permission and must be installed before the app, uninstall the store and your app and install the store (1) and the app(2) again.
--
Отправлено из Mail.Ru для Android суббота, 11 июля 2015г., 11:14 +03:00 от alex-dorokhov < notifications@github.com> :

>openiab 0.9.8.7
>java.lang.SecurityException: Not allowed to bind to service Intent { act=org.onepf.oms.openappstore.BIND cmp=com.yandex.store/.service.YandexStoreService }
       at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1675)
       at android.app.ContextImpl.bindService(ContextImpl.java:1639)
       at android.content.ContextWrapper.bindService(ContextWrapper.java:517)
       at org.onepf.oms.OpenIabHelper.discoverOpenStores(OpenIabHelper.java:1036)
       at org.onepf.oms.OpenIabHelper.discoverOpenStores(OpenIabHelper.java:1001)
       at org.onepf.oms.OpenIabHelper.setup(OpenIabHelper.java:694)
       at org.onepf.oms.OpenIabHelper.setupWithStrategy(OpenIabHelper.java:579)
       at org.onepf.oms.OpenIabHelper.startSetup(OpenIabHelper.java:550)
       at com.badlogic.gdx.pay.android.openiab.PurchaseManagerAndroidOpenIAB$1.run(PurchaseManagerAndroidOpenIAB.java:232)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5292)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
       at dalvik.system.NativeStart.main(NativeStart.java)
