### ISSUE TITLE
Lollipop 5.0.2, OpenIAB 0.9.8.7 and 0.9.8.6, Amazon store: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=org.onepf.oms.billing.BIND }

### ISSUE THREAD

**Issue by clorteau** [onepf/OpenIAB#500]
Hi. On 0.9.8.6 and 0.9.8.7 I still get this bug. Phone is Galaxy S6 with lollipop 5.0.2.

java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=org.onepf.oms.billing.BIND }
at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:2053)
at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:2161)
at android.app.ContextImpl.bindService(ContextImpl.java:2139)
at android.content.ContextWrapper.bindService(ContextWrapper.java:559)
at org.onepf.oms.appstore.googleUtils.IabHelper.startSetup(IabHelper.java:277)
at org.onepf.oms.OpenIabHelper$12$1.onIabSetupFinished(OpenIabHelper.java:863)
at org.onepf.oms.OpenIabHelper.finishSetup(OpenIabHelper.java:952)
at org.onepf.oms.OpenIabHelper.finishSetup(OpenIabHelper.java:921)
at org.onepf.oms.OpenIabHelper.access$1800(OpenIabHelper.java:85)
at org.onepf.oms.OpenIabHelper$12$2.run(OpenIabHelper.java:872)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:6117)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by deko519** [comment]
I confirm the issue on Nexus 7 2013, android  5.1.1. I use 0.9.8.7.

E/AndroidRuntime(16142): FATAL EXCEPTION: main
E/AndroidRuntime(16142): Process: com.js_ex.jeweltree, PID: 16142
E/AndroidRuntime(16142): java.lang.SecurityException: Not allowed to bind to service Intent { act=org.onepf.oms.openappstore.BIND cmp=com.yandex.store/.service.YandexStoreService }
E/AndroidRuntime(16142): 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1793)
E/AndroidRuntime(16142): 	at android.app.ContextImpl.bindService(ContextImpl.java:1757)
E/AndroidRuntime(16142): 	at android.content.ContextWrapper.bindService(ContextWrapper.java:539)
E/AndroidRuntime(16142): 	at org.onepf.oms.OpenIabHelper.discoverOpenStores(OpenIabHelper.java:1036)
E/AndroidRuntime(16142): 	at org.onepf.oms.OpenIabHelper.discoverOpenStores(OpenIabHelper.java:1001)
E/AndroidRuntime(16142): 	at org.onepf.oms.OpenIabHelper.setup(OpenIabHelper.java:694)
E/AndroidRuntime(16142): 	at org.onepf.oms.OpenIabHelper.setupWithStrategy(OpenIabHelper.java:579)
E/AndroidRuntime(16142): 	at org.onepf.oms.OpenIabHelper.startSetup(OpenIabHelper.java:550)
E/AndroidRuntime(16142): 	at com.js.helpers.IAPHelper$1.run(IAPHelper.java:96)
E/AndroidRuntime(16142): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(16142): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(16142): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(16142): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime(16142): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16142): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(16142): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(16142): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
W/ActivityManager(  552):   Force finishing activity 1 com.js_ex.jeweltree/com.js.helpers.JSNativeActivity

**Comment by UrbanKristan** [comment]
Same error on SlideMe. Nexus 7 Lollipop 5.1.1.  openIab 0.9.8.6

E/AndroidRuntime( 8890): Process: com.mindtheoverlap1.game.android, PID: 8890
E/AndroidRuntime( 8890): java.lang.IllegalArgumentException: Service Intent must
 be explicit: Intent { act=org.onepf.oms.billing.BIND }
E/AndroidRuntime( 8890):        at android.app.ContextImpl.validateServiceIntent
(ContextImpl.java:1680)
E/AndroidRuntime( 8890):        at android.app.ContextImpl.bindServiceCommon(Con
textImpl.java:1779)
E/AndroidRuntime( 8890):        at android.app.ContextImpl.bindService(ContextIm
pl.java:1757)
E/AndroidRuntime( 8890):        at android.content.ContextWrapper.bindService(Co
ntextWrapper.java:539)
E/AndroidRuntime( 8890):        at org.onepf.oms.appstore.googleUtils.IabHelper.
startSetup(IabHelper.java:277)
E/AndroidRuntime( 8890):        at org.onepf.oms.OpenIabHelper$12$1.onIabSetupFi
nished(OpenIabHelper.java:863)
E/AndroidRuntime( 8890):        at org.onepf.oms.OpenIabHelper.finishSetup(OpenI
abHelper.java:952)
E/AndroidRuntime( 8890):        at org.onepf.oms.OpenIabHelper.finishSetup(OpenI
abHelper.java:921)
E/AndroidRuntime( 8890):        at org.onepf.oms.OpenIabHelper.access$1800(OpenI
abHelper.java:85)
E/AndroidRuntime( 8890):        at org.onepf.oms.OpenIabHelper$12$2.run(OpenIabH
elper.java:872)
E/AndroidRuntime( 8890):        at android.os.Handler.handleCallback(Handler.jav
a:739)
E/AndroidRuntime( 8890):        at android.os.Handler.dispatchMessage(Handler.ja
va:95)
E/AndroidRuntime( 8890):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 8890):        at android.app.ActivityThread.main(ActivityThrea
d.java:5254)
E/AndroidRuntime( 8890):        at java.lang.reflect.Method.invoke(Native Method
)
E/AndroidRuntime( 8890):        at java.lang.reflect.Method.invoke(Method.java:3
72)
E/AndroidRuntime( 8890):        at com.android.internal.os.ZygoteInit$MethodAndA
rgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 8890):        at com.android.internal.os.ZygoteInit.main(Zygot
eInit.java:698)
I/ActivityManager(  537): Displayed com.mindtheoverlap1.game.android/.AndroidLau
ncher: +469ms
W/ActivityManager(  537):   Force finishing activity 1 com.mindtheoverlap1.game.
android/.AndroidLauncher
W/ActivityManager(  537):   Force finishing activity 2 com.slideme.sam.manager/.

**Comment by akarimova** [comment]
looks like a oem issue :(

**Comment by peterdk** [comment]
Same error with Slideme. This really should be fixed, it also affects OpenIAB stores.
