### ISSUE TITLE
Unable to instantiate receiver com.amazon.device.iap.ResponseReceiver: java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by silent1** [onepf/OpenIAB#501]
I'm getting this exception on some devices when the apk is installed through the Google Play Store:

java.lang.RuntimeException: Unable to instantiate receiver com.amazon.device.iap.ResponseReceiver: java.lang.ClassNotFoundException: Didn't find class "com.amazon.device.iap.ResponseReceiver" on path: DexPathList[[zip file "/data/app/com.kwad.chime-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.kwad.chime-1, /vendor/lib, /system/lib]]
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2450)
	at android.app.ActivityThread.access$1700(ActivityThread.java:149)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1286)
	at android.os.Handler.dispatchMessage(Handler.java:122)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5122)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.amazon.device.iap.ResponseReceiver" on path: DexPathList[[zip file "/data/app/com.kwad.chime-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.kwad.chime-1, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:67)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.lang.ClassLoader._logged_loadClass(ClassLoader.java:480)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:472)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2445)
	... 10 more

I have 
`<receiver android:name="com.amazon.device.iap.ResponseReceiver">
            <intent-filter>
                <action
                    android:name="com.amazon.inapp.purchasing.NOTIFY"
                    android:permission="com.amazon.inapp.purchasing.Permission.NOTIFY" />
            </intent-filter>
        </receiver>`
 included in my AndroidManifest file, as outlined in the OpenIab Sample application since I also put the apk in the Amazon App Store. 

What is going on with the installations through Google Play? I've seen this on at least a Nexus 5 running 4.4.2 and a Nexus 6 running 5.0.2

**Comment by silent1** [comment]
The apk was using OpenIAB version 0.9.8.6

**Comment by akarimova** [comment]
@RomanZhilich please help

**Comment by TobyKaos** [comment]
I have same with Amazon Fire TV.
