### ISSUE TITLE
java.lang.IllegalStateException using latest build

### ISSUE THREAD

**Issue by ahmedbaracat** [onepf/OpenIAB#510]
java.lang.IllegalStateException: IAB helper setup failed. Can't perform operation: queryInventory
at org.onepf.oms.OpenIabHelper.checkSetupDone(OpenIabHelper.java:1517)
at org.onepf.oms.OpenIabHelper.queryInventoryAsync(OpenIabHelper.java:1413)
at org.onepf.oms.OpenIabHelper.queryInventoryAsync(OpenIabHelper.java:1395)
at org.onepf.oms.OpenIabHelper.queryInventoryAsync(OpenIabHelper.java:1386)
at org.onepf.oms.OpenIabHelper.queryInventoryAsync(OpenIabHelper.java:1378)
at org.onepf.openiab.UnityPlugin$2.run(UnityPlugin.java:147)
at android.os.Handler.handleCallback(Handler.java:615)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4745)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
at dalvik.system.NativeStart.main(Native Method)

**Comment by nanom1t** [comment]
Nokia X/XL

java.lang.IllegalStateException
org.onepf.oms.OpenIabHelper.checkBillingAndFinish(OpenIabHelper.java:780)
org.onepf.oms.OpenIabHelper.access$1300(OpenIabHelper.java:84)
org.onepf.oms.OpenIabHelper$10.openStoresDiscovered(OpenIabHelper.java:724)
org.onepf.oms.OpenIabHelper.discoverOpenStores(OpenIabHelper.java:1046)
org.onepf.oms.OpenIabHelper.access$2000(OpenIabHelper.java:84)
org.onepf.oms.OpenIabHelper$14.onServiceConnected(OpenIabHelper.java:1025)
android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1097)
android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1114)
android.os.Handler.handleCallback(Handler.java:615)
android.os.Handler.dispatchMessage(Handler.java:92)
android.os.Looper.loop(Looper.java:137)
android.app.ActivityThread.main(ActivityThread.java:4813)
java.lang.reflect.Method.invokeNative(Native Method)
java.lang.reflect.Method.invoke(Method.java:511)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:559)
dalvik.system.NativeStart.main(Native Method)
