### ISSUE TITLE
Yandex Store issue with unity plugin 0.9.8.6

### ISSUE THREAD

**Issue by sanmn19** [onepf/OpenIAB#515]
I have integrated the plugin and calling with only Yandex in the storeKeys. I have pasted the key correctly. My game crashes and I am getting the following error. The jar openIAB-plugin.jar is present in Plugins/Android/. Also, I re-imported the plugin but issue persists. I have yandex store installed and I have logged in.

I/Unity   (22743): ********** Android OpenIAB plugin initialized **********
I/Unity   (22743):  
I/Unity   (22743): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   (22743): 
D/OpenIAB-UnityPlugin(22743): createBroadcasts
D/OpenIAB-UnityPlugin(22743): Starting setup.
D/YandexStoreService( 5793): [YandexStoreService] getInAppBillingServiceIntent
I/art     (22743): Rejecting re-init on previously-failed class java.lang.Class<org.onepf.oms.appstore.OpenAppstore$IOpenInAppBillingWrapper>
I/art     (22743): Rejecting re-init on previously-failed class java.lang.Class<org.onepf.oms.appstore.OpenAppstore$IOpenInAppBillingWrapper>
D/YandexStoreService( 5793): [YandexStoreService] Call IOpenAppstore$Stub.isBillingAvailable for package: <myAppPackage
V/AsyncHttpResponseHandler(22743): Progress 16 from 1 (1600%)
I/art     (22743): Rejecting re-init on previously-failed class java.lang.Class<org.onepf.oms.appstore.OpenAppstore$IOpenInAppBillingWrapper>
D/AndroidRuntime(22743): Shutting down VM
--------- beginning of crash
E/AndroidRuntime(22743): FATAL EXCEPTION: main
E/AndroidRuntime(22743): Process: <myAppPackage, PID: 22743
E/AndroidRuntime(22743): java.lang.Error: FATAL EXCEPTION [main]
E/AndroidRuntime(22743): Unity version     : 5.1.4f1
E/AndroidRuntime(22743): Device model      : motorola XT1052
E/AndroidRuntime(22743): 
E/AndroidRuntime(22743): Caused by: java.lang.NoClassDefFoundError: org.onepf.oms.appstore.OpenAppstore$IOpenInAppBillingWrapper
E/AndroidRuntime(22743): 	at org.onepf.oms.appstore.OpenAppstore$1.getServiceFromBinder(OpenAppstore.java:76)
E/AndroidRuntime(22743): 	at org.onepf.oms.appstore.googleUtils.IabHelper$1.onServiceConnected(IabHelper.java:229)
E/AndroidRuntime(22743): 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1208)
E/AndroidRuntime(22743): 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1225)
E/AndroidRuntime(22743): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(22743): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(22743): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(22743): 	at android.app.ActivityThread.main(ActivityThread.java:5343)
E/AndroidRuntime(22743): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22743): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(22743): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
E/AndroidRuntime(22743): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by sanmn19** [comment]
Sorry. Created it in the right place
https://github.com/onepf/OpenIAB-Unity-Plugin/issues/87
