### ISSUE TITLE
Proguard configuration for the library

### ISSUE THREAD

**Issue by WebDucer** [onepf/OpenIAB#82]
After switching from GoolgePlay in app library to OpenIAB I got the following errors if I try to compile with proguard on.

I used the snippets of proguard configuration for google IAB and amazon IAB.

```
[2013-12-30 20:07:48] Proguard returned with error code 1. See console
[2013-12-30 20:07:48] Note: there were 2 duplicate class definitions.
[2013-12-30 20:07:48] Warning: com.google.android.gms.internal.ct: can't find referenced method 'android.webkit.WebResourceResponse shouldInterceptRequest(android.webkit.WebView,java.lang.String)' in class com.google.android.gms.internal.cr
[2013-12-30 20:07:48] Warning: library class android.webkit.WebView depends on program class android.webkit.WebViewClient
[2013-12-30 20:07:48]       You should check if you need to specify additional program jars.
[2013-12-30 20:07:48] Warning: there were 1 instances of library classes depending on program classes.
[2013-12-30 20:07:48]          You must avoid such dependencies, since the program classes will
[2013-12-30 20:07:48]          be processed, while the library classes will remain unchanged.
[2013-12-30 20:07:48] Warning: there were 1 unresolved references to program class members.
[2013-12-30 20:07:48]          Your input classes appear to be inconsistent.
[2013-12-30 20:07:48]          You may need to recompile them and try again.
[2013-12-30 20:07:48]          Alternatively, you may have to specify the option 
[2013-12-30 20:07:48]          '-dontskipnonpubliclibraryclassmembers'.
[2013-12-30 20:07:48] java.io.IOException: Please correct the above warnings first.
[2013-12-30 20:07:48]   at proguard.Initializer.execute(Initializer.java:321)
[2013-12-30 20:07:48]   at proguard.ProGuard.initialize(ProGuard.java:211)
[2013-12-30 20:07:48]   at proguard.ProGuard.execute(ProGuard.java:86)
[2013-12-30 20:07:48]   at proguard.ProGuard.main(ProGuard.java:492)
```

I use the following libraries beside OpenIAB
- ACRA (Application Crash Report for Android)
- Android Support v7 (AppCompat)
- Android Support v4
- Google Play Services

**Comment by afgaiel** [comment]
you are really crazy girl, only your two lines solved my bloody problem after 2 days of hill searching for solution.
